<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GFKKN7N" failures="1" tests="11" name="Test_Case_LoginPage" time="45.064" errors="0" timestamp="2023-02-02T09:31:50 ICT">
  <testcase classname="com.easyserv.testcases.Admin.UserAccessTest" name="LoginTest_TC001" time="1.036"/>
  <testcase classname="com.easyserv.testcases.Admin.UserAccessTest" name="LoginTest_TC002" time="5.823"/>
  <testcase classname="com.easyserv.testcases.Admin.UserAccessTest" name="LoginTest_TC003" time="0.947"/>
  <testcase classname="com.easyserv.testcases.Admin.UserAccessTest" name="LoginTest_TC004" time="1.02"/>
  <testcase classname="com.easyserv.testcases.Admin.UserAccessTest" name="LoginTest_TC005" time="3.626"/>
  <testcase classname="com.easyserv.testcases.Admin.UserAccessTest" name="LoginTest_TC006" time="1.309"/>
  <testcase classname="com.easyserv.testcases.Admin.UserAccessTest" name="LoginTest_TC007" time="1.692"/>
  <testcase classname="com.easyserv.testcases.Admin.UserAccessTest" name="LoginTest_TC008" time="1.163"/>
  <testcase classname="com.easyserv.testcases.Admin.UserAccessTest" name="LoginTest_TC009" time="7.436"/>
  <testcase classname="com.easyserv.testcases.Admin.UserAccessTest" name="LoginTest_TC010" time="2.489"/>
  <testcase classname="com.easyserv.testcases.Admin.UserAccessTest" name="LoginTest_TC011" time="2.801">
    <failure type="java.lang.AssertionError" message="expected [Global] but found [Baldivis]">
      <![CDATA[java.lang.AssertionError: expected [Global] but found [Baldivis]
at com.easyserv.testcases.Admin.UserAccessTest.LoginTest_TC011(UserAccessTest.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- LoginTest_TC011 -->
</testsuite> <!-- Test_Case_LoginPage -->
